version: "3.6"

services:
  nginx-angular:
    image: nginx:1.13
    restart: always
    ports:  
      - "80:80"
    volumes:
      - ./prueba/dist/prueba:/usr/share/nginx/html
    depends_on:
      - nginx-spring

  nginx-spring:
    image: nginx:1.13
    restart: always
    ports: 
      - "90:90"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    command: mvn clean spring-boot:run
    volumes:
      - ./demo:/demo
      - ~/.m2:/root/.m2
    expose:  
      - "8080"
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_DB=prueba
      - POSTGRES_USER=fabricio
      - POSTGRES_PASSWORD=Assemblix86
    expose:
      - "5432"